<?php

namespace PHPMaker2024\sgq;

// Navbar menu
$topMenu = new Menu("navbar", true, true);
$topMenu->addMenuItem(173, "mi_Dashboard2", $Language->menuPhrase("173", "MenuText"), "Dashboard2", -1, "", AllowListMenu('{E0FBA0D0-6EA0-4AAB-A8CC-5871C01EDF16}Dashboard'), false, false, "", "", true, false);
$topMenu->addMenuItem(168, "mci_Auditoria", $Language->menuPhrase("168", "MenuText"), "", -1, "", true, false, true, "", "", true, false);
$topMenu->addMenuItem(67, "mi_analise_critica_direcao", $Language->menuPhrase("67", "MenuText"), "AnaliseCriticaDirecaoList", 168, "", AllowListMenu('{E0FBA0D0-6EA0-4AAB-A8CC-5871C01EDF16}analise_critica_direcao'), false, false, "", "", true, false);
$topMenu->addMenuItem(66, "mi_relatorio_auditoria_interna", $Language->menuPhrase("66", "MenuText"), "RelatorioAuditoriaInternaList", 168, "", AllowListMenu('{E0FBA0D0-6EA0-4AAB-A8CC-5871C01EDF16}relatorio_auditoria_interna'), false, false, "", "", true, false);
$topMenu->addMenuItem(69, "mi_plano_auditoria_int", $Language->menuPhrase("69", "MenuText"), "PlanoAuditoriaIntList", 168, "", AllowListMenu('{E0FBA0D0-6EA0-4AAB-A8CC-5871C01EDF16}plano_auditoria_int'), false, false, "", "", true, false);
$topMenu->addMenuItem(70, "mi_relatorio_aud_int", $Language->menuPhrase("70", "MenuText"), "RelatorioAudIntList?cmd=resetall", 168, "", AllowListMenu('{E0FBA0D0-6EA0-4AAB-A8CC-5871C01EDF16}relatorio_aud_int'), false, false, "", "", true, false);
$topMenu->addMenuItem(121, "mci_Contexto_Org", $Language->menuPhrase("121", "MenuText"), "", -1, "", true, false, true, "", "", true, false);
$topMenu->addMenuItem(50, "mi_analise_negocio", $Language->menuPhrase("50", "MenuText"), "AnaliseNegocioList", 121, "", AllowListMenu('{E0FBA0D0-6EA0-4AAB-A8CC-5871C01EDF16}analise_negocio'), false, false, "", "", true, false);
$topMenu->addMenuItem(56, "mi_contexto", $Language->menuPhrase("56", "MenuText"), "ContextoList", 121, "", AllowListMenu('{E0FBA0D0-6EA0-4AAB-A8CC-5871C01EDF16}contexto'), false, false, "", "", true, false);
$topMenu->addMenuItem(51, "mi_objetivo_qualidade", $Language->menuPhrase("51", "MenuText"), "ObjetivoQualidadeList", 121, "", AllowListMenu('{E0FBA0D0-6EA0-4AAB-A8CC-5871C01EDF16}objetivo_qualidade'), false, false, "", "", true, false);
$topMenu->addMenuItem(7, "mi_processo", $Language->menuPhrase("7", "MenuText"), "ProcessoList", 121, "", AllowListMenu('{E0FBA0D0-6EA0-4AAB-A8CC-5871C01EDF16}processo'), false, false, "", "", true, false);
$topMenu->addMenuItem(14, "mci_Documentos", $Language->menuPhrase("14", "MenuText"), "", -1, "", true, false, true, "", "", true, false);
$topMenu->addMenuItem(4, "mi_documento_interno", $Language->menuPhrase("4", "MenuText"), "DocumentoInternoList", 14, "", AllowListMenu('{E0FBA0D0-6EA0-4AAB-A8CC-5871C01EDF16}documento_interno'), false, false, "", "", true, false);
$topMenu->addMenuItem(3, "mi_documento_externo", $Language->menuPhrase("3", "MenuText"), "DocumentoExternoList", 14, "", AllowListMenu('{E0FBA0D0-6EA0-4AAB-A8CC-5871C01EDF16}documento_externo'), false, false, "", "", true, false);
$topMenu->addMenuItem(5, "mi_documento_registro", $Language->menuPhrase("5", "MenuText"), "DocumentoRegistroList", 14, "", AllowListMenu('{E0FBA0D0-6EA0-4AAB-A8CC-5871C01EDF16}documento_registro'), false, false, "", "", true, false);
$topMenu->addMenuItem(8, "mi_revisao_documento", $Language->menuPhrase("8", "MenuText"), "RevisaoDocumentoList?cmd=resetall", 14, "", AllowListMenu('{E0FBA0D0-6EA0-4AAB-A8CC-5871C01EDF16}revisao_documento'), false, false, "", "", true, false);
$topMenu->addMenuItem(49, "mi_gestao_mudanca", $Language->menuPhrase("49", "MenuText"), "GestaoMudancaList", -1, "", AllowListMenu('{E0FBA0D0-6EA0-4AAB-A8CC-5871C01EDF16}gestao_mudanca'), false, false, "", "", true, false);
$topMenu->addMenuItem(17, "mi_indicadores", $Language->menuPhrase("17", "MenuText"), "IndicadoresList", -1, "", AllowListMenu('{E0FBA0D0-6EA0-4AAB-A8CC-5871C01EDF16}indicadores'), false, false, "", "", true, false);
$topMenu->addMenuItem(47, "mi_nao_conformidade", $Language->menuPhrase("47", "MenuText"), "NaoConformidadeList", -1, "", AllowListMenu('{E0FBA0D0-6EA0-4AAB-A8CC-5871C01EDF16}nao_conformidade'), false, false, "", "", true, false);
$topMenu->addMenuItem(23, "mi_risco_oportunidade", $Language->menuPhrase("23", "MenuText"), "RiscoOportunidadeList", -1, "", AllowListMenu('{E0FBA0D0-6EA0-4AAB-A8CC-5871C01EDF16}risco_oportunidade'), false, false, "", "", true, false);
$topMenu->addMenuItem(10, "mci_Tabelas", $Language->menuPhrase("10", "MenuText"), "", -1, "", true, false, true, "", "", true, false);
$topMenu->addMenuItem(2, "mi_categoria_documento", $Language->menuPhrase("2", "MenuText"), "CategoriaDocumentoList", 10, "", AllowListMenu('{E0FBA0D0-6EA0-4AAB-A8CC-5871C01EDF16}categoria_documento'), false, false, "", "", true, false);
$topMenu->addMenuItem(54, "mi_consideracoes", $Language->menuPhrase("54", "MenuText"), "ConsideracoesList", 10, "", AllowListMenu('{E0FBA0D0-6EA0-4AAB-A8CC-5871C01EDF16}consideracoes'), false, false, "", "", true, false);
$topMenu->addMenuItem(57, "mi_competencia", $Language->menuPhrase("57", "MenuText"), "CompetenciaList", 10, "", AllowListMenu('{E0FBA0D0-6EA0-4AAB-A8CC-5871C01EDF16}competencia'), false, false, "", "", true, false);
$topMenu->addMenuItem(45, "mi_departamentos", $Language->menuPhrase("45", "MenuText"), "DepartamentosList", 10, "", AllowListMenu('{E0FBA0D0-6EA0-4AAB-A8CC-5871C01EDF16}departamentos'), false, false, "", "", true, false);
$topMenu->addMenuItem(6, "mi_localizacao", $Language->menuPhrase("6", "MenuText"), "LocalizacaoList", 10, "", AllowListMenu('{E0FBA0D0-6EA0-4AAB-A8CC-5871C01EDF16}localizacao'), false, false, "", "", true, false);
$topMenu->addMenuItem(9, "mi_status_documento", $Language->menuPhrase("9", "MenuText"), "StatusDocumentoList", 10, "", AllowListMenu('{E0FBA0D0-6EA0-4AAB-A8CC-5871C01EDF16}status_documento'), false, false, "", "", true, false);
$topMenu->addMenuItem(41, "mci_Risco/Oportunidade", $Language->menuPhrase("41", "MenuText"), "", 10, "", true, false, true, "", "", true, false);
$topMenu->addMenuItem(19, "mi_acao_risco_oportunidade", $Language->menuPhrase("19", "MenuText"), "AcaoRiscoOportunidadeList", 41, "", AllowListMenu('{E0FBA0D0-6EA0-4AAB-A8CC-5871C01EDF16}acao_risco_oportunidade'), false, false, "", "", true, false);
$topMenu->addMenuItem(20, "mi_frequencia", $Language->menuPhrase("20", "MenuText"), "FrequenciaList", 41, "", AllowListMenu('{E0FBA0D0-6EA0-4AAB-A8CC-5871C01EDF16}frequencia'), false, false, "", "", true, false);
$topMenu->addMenuItem(21, "mi_impacto", $Language->menuPhrase("21", "MenuText"), "ImpactoList", 41, "", AllowListMenu('{E0FBA0D0-6EA0-4AAB-A8CC-5871C01EDF16}impacto'), false, false, "", "", true, false);
$topMenu->addMenuItem(22, "mi_origem_risco_oportunidade", $Language->menuPhrase("22", "MenuText"), "OrigemRiscoOportunidadeList", 41, "", AllowListMenu('{E0FBA0D0-6EA0-4AAB-A8CC-5871C01EDF16}origem_risco_oportunidade'), false, false, "", "", true, false);
$topMenu->addMenuItem(42, "mi_periodicidade", $Language->menuPhrase("42", "MenuText"), "PeriodicidadeList", 41, "", AllowListMenu('{E0FBA0D0-6EA0-4AAB-A8CC-5871C01EDF16}periodicidade'), false, false, "", "", true, false);
$topMenu->addMenuItem(24, "mi_status_acao", $Language->menuPhrase("24", "MenuText"), "StatusAcaoList", 41, "", AllowListMenu('{E0FBA0D0-6EA0-4AAB-A8CC-5871C01EDF16}status_acao'), false, false, "", "", true, false);
$topMenu->addMenuItem(174, "mi_tipo", $Language->menuPhrase("174", "MenuText"), "TipoList", 10, "", AllowListMenu('{E0FBA0D0-6EA0-4AAB-A8CC-5871C01EDF16}tipo'), false, false, "", "", true, false);
$topMenu->addMenuItem(64, "mi_unidade_medida", $Language->menuPhrase("64", "MenuText"), "UnidadeMedidaList", 10, "", AllowListMenu('{E0FBA0D0-6EA0-4AAB-A8CC-5871C01EDF16}unidade_medida'), false, false, "", "", true, false);
$topMenu->addMenuItem(11, "mci_Segurança", $Language->menuPhrase("11", "MenuText"), "", 10, "", true, false, true, "", "", true, false);
$topMenu->addMenuItem(1, "mi_usuario", $Language->menuPhrase("1", "MenuText"), "UsuarioList", 11, "", AllowListMenu('{E0FBA0D0-6EA0-4AAB-A8CC-5871C01EDF16}usuario'), false, false, "", "", true, false);
$topMenu->addMenuItem(53, "mi_UserLevels", $Language->menuPhrase("53", "MenuText"), "UserLevelsList", 11, "", AllowListMenu('{E0FBA0D0-6EA0-4AAB-A8CC-5871C01EDF16}UserLevels'), false, false, "", "", true, false);
$topMenu->addMenuItem(16, "mci_Relatórios", $Language->menuPhrase("16", "MenuText"), "", -1, "", true, false, true, "", "", true, false);
$topMenu->addMenuItem(55, "mi_rel_analise_swot", $Language->menuPhrase("55", "MenuText"), "RelAnaliseSwot", 16, "", AllowListMenu('{E0FBA0D0-6EA0-4AAB-A8CC-5871C01EDF16}rel_analise_swot'), false, false, "", "", true, false);
$topMenu->addMenuItem(59, "mi_rel_cross_grafico", $Language->menuPhrase("59", "MenuText"), "RelCrossGrafico", 16, "", AllowListMenu('{E0FBA0D0-6EA0-4AAB-A8CC-5871C01EDF16}rel_cross_grafico'), false, false, "", "", true, false);
$topMenu->addMenuItem(172, "mi_rel_view_plano_auditoria", $Language->menuPhrase("172", "MenuText"), "RelViewPlanoAuditoria", 16, "", AllowListMenu('{E0FBA0D0-6EA0-4AAB-A8CC-5871C01EDF16}rel_view_plano_auditoria'), false, false, "", "", true, false);
$topMenu->addMenuItem(63, "mi_rel_processos", $Language->menuPhrase("63", "MenuText"), "RelProcessos", 16, "", AllowListMenu('{E0FBA0D0-6EA0-4AAB-A8CC-5871C01EDF16}rel_processos'), false, false, "", "", true, false);
$topMenu->addMenuItem(62, "mi_rel_processo_indicador", $Language->menuPhrase("62", "MenuText"), "RelProcessoIndicador", 16, "", AllowListMenu('{E0FBA0D0-6EA0-4AAB-A8CC-5871C01EDF16}rel_processo_indicador'), false, false, "", "", true, false);
$topMenu->addMenuItem(170, "mi_rel_view_aud_interna", $Language->menuPhrase("170", "MenuText"), "RelViewAudInterna", 16, "", AllowListMenu('{E0FBA0D0-6EA0-4AAB-A8CC-5871C01EDF16}rel_view_aud_interna'), false, false, "", "", true, false);
echo $topMenu->toScript();

// Sidebar menu
$sideMenu = new Menu("menu", true, false);
$sideMenu->addMenuItem(173, "mi_Dashboard2", $Language->menuPhrase("173", "MenuText"), "Dashboard2", -1, "", AllowListMenu('{E0FBA0D0-6EA0-4AAB-A8CC-5871C01EDF16}Dashboard'), false, false, "", "", true, true);
$sideMenu->addMenuItem(168, "mci_Auditoria", $Language->menuPhrase("168", "MenuText"), "", -1, "", true, false, true, "", "", true, true);
$sideMenu->addMenuItem(67, "mi_analise_critica_direcao", $Language->menuPhrase("67", "MenuText"), "AnaliseCriticaDirecaoList", 168, "", AllowListMenu('{E0FBA0D0-6EA0-4AAB-A8CC-5871C01EDF16}analise_critica_direcao'), false, false, "", "", true, true);
$sideMenu->addMenuItem(66, "mi_relatorio_auditoria_interna", $Language->menuPhrase("66", "MenuText"), "RelatorioAuditoriaInternaList", 168, "", AllowListMenu('{E0FBA0D0-6EA0-4AAB-A8CC-5871C01EDF16}relatorio_auditoria_interna'), false, false, "", "", true, true);
$sideMenu->addMenuItem(69, "mi_plano_auditoria_int", $Language->menuPhrase("69", "MenuText"), "PlanoAuditoriaIntList", 168, "", AllowListMenu('{E0FBA0D0-6EA0-4AAB-A8CC-5871C01EDF16}plano_auditoria_int'), false, false, "", "", true, true);
$sideMenu->addMenuItem(70, "mi_relatorio_aud_int", $Language->menuPhrase("70", "MenuText"), "RelatorioAudIntList?cmd=resetall", 168, "", AllowListMenu('{E0FBA0D0-6EA0-4AAB-A8CC-5871C01EDF16}relatorio_aud_int'), false, false, "", "", true, true);
$sideMenu->addMenuItem(121, "mci_Contexto_Org", $Language->menuPhrase("121", "MenuText"), "", -1, "", true, false, true, "", "", true, true);
$sideMenu->addMenuItem(50, "mi_analise_negocio", $Language->menuPhrase("50", "MenuText"), "AnaliseNegocioList", 121, "", AllowListMenu('{E0FBA0D0-6EA0-4AAB-A8CC-5871C01EDF16}analise_negocio'), false, false, "", "", true, true);
$sideMenu->addMenuItem(56, "mi_contexto", $Language->menuPhrase("56", "MenuText"), "ContextoList", 121, "", AllowListMenu('{E0FBA0D0-6EA0-4AAB-A8CC-5871C01EDF16}contexto'), false, false, "", "", true, true);
$sideMenu->addMenuItem(51, "mi_objetivo_qualidade", $Language->menuPhrase("51", "MenuText"), "ObjetivoQualidadeList", 121, "", AllowListMenu('{E0FBA0D0-6EA0-4AAB-A8CC-5871C01EDF16}objetivo_qualidade'), false, false, "", "", true, true);
$sideMenu->addMenuItem(7, "mi_processo", $Language->menuPhrase("7", "MenuText"), "ProcessoList", 121, "", AllowListMenu('{E0FBA0D0-6EA0-4AAB-A8CC-5871C01EDF16}processo'), false, false, "", "", true, true);
$sideMenu->addMenuItem(14, "mci_Documentos", $Language->menuPhrase("14", "MenuText"), "", -1, "", true, false, true, "", "", true, true);
$sideMenu->addMenuItem(4, "mi_documento_interno", $Language->menuPhrase("4", "MenuText"), "DocumentoInternoList", 14, "", AllowListMenu('{E0FBA0D0-6EA0-4AAB-A8CC-5871C01EDF16}documento_interno'), false, false, "", "", true, true);
$sideMenu->addMenuItem(3, "mi_documento_externo", $Language->menuPhrase("3", "MenuText"), "DocumentoExternoList", 14, "", AllowListMenu('{E0FBA0D0-6EA0-4AAB-A8CC-5871C01EDF16}documento_externo'), false, false, "", "", true, true);
$sideMenu->addMenuItem(5, "mi_documento_registro", $Language->menuPhrase("5", "MenuText"), "DocumentoRegistroList", 14, "", AllowListMenu('{E0FBA0D0-6EA0-4AAB-A8CC-5871C01EDF16}documento_registro'), false, false, "", "", true, true);
$sideMenu->addMenuItem(8, "mi_revisao_documento", $Language->menuPhrase("8", "MenuText"), "RevisaoDocumentoList?cmd=resetall", 14, "", AllowListMenu('{E0FBA0D0-6EA0-4AAB-A8CC-5871C01EDF16}revisao_documento'), false, false, "", "", true, true);
$sideMenu->addMenuItem(49, "mi_gestao_mudanca", $Language->menuPhrase("49", "MenuText"), "GestaoMudancaList", -1, "", AllowListMenu('{E0FBA0D0-6EA0-4AAB-A8CC-5871C01EDF16}gestao_mudanca'), false, false, "", "", true, true);
$sideMenu->addMenuItem(17, "mi_indicadores", $Language->menuPhrase("17", "MenuText"), "IndicadoresList", -1, "", AllowListMenu('{E0FBA0D0-6EA0-4AAB-A8CC-5871C01EDF16}indicadores'), false, false, "", "", true, true);
$sideMenu->addMenuItem(47, "mi_nao_conformidade", $Language->menuPhrase("47", "MenuText"), "NaoConformidadeList", -1, "", AllowListMenu('{E0FBA0D0-6EA0-4AAB-A8CC-5871C01EDF16}nao_conformidade'), false, false, "", "", true, true);
$sideMenu->addMenuItem(23, "mi_risco_oportunidade", $Language->menuPhrase("23", "MenuText"), "RiscoOportunidadeList", -1, "", AllowListMenu('{E0FBA0D0-6EA0-4AAB-A8CC-5871C01EDF16}risco_oportunidade'), false, false, "", "", true, true);
$sideMenu->addMenuItem(10, "mci_Tabelas", $Language->menuPhrase("10", "MenuText"), "", -1, "", true, false, true, "", "", true, true);
$sideMenu->addMenuItem(2, "mi_categoria_documento", $Language->menuPhrase("2", "MenuText"), "CategoriaDocumentoList", 10, "", AllowListMenu('{E0FBA0D0-6EA0-4AAB-A8CC-5871C01EDF16}categoria_documento'), false, false, "", "", true, true);
$sideMenu->addMenuItem(54, "mi_consideracoes", $Language->menuPhrase("54", "MenuText"), "ConsideracoesList", 10, "", AllowListMenu('{E0FBA0D0-6EA0-4AAB-A8CC-5871C01EDF16}consideracoes'), false, false, "", "", true, true);
$sideMenu->addMenuItem(57, "mi_competencia", $Language->menuPhrase("57", "MenuText"), "CompetenciaList", 10, "", AllowListMenu('{E0FBA0D0-6EA0-4AAB-A8CC-5871C01EDF16}competencia'), false, false, "", "", true, true);
$sideMenu->addMenuItem(45, "mi_departamentos", $Language->menuPhrase("45", "MenuText"), "DepartamentosList", 10, "", AllowListMenu('{E0FBA0D0-6EA0-4AAB-A8CC-5871C01EDF16}departamentos'), false, false, "", "", true, true);
$sideMenu->addMenuItem(6, "mi_localizacao", $Language->menuPhrase("6", "MenuText"), "LocalizacaoList", 10, "", AllowListMenu('{E0FBA0D0-6EA0-4AAB-A8CC-5871C01EDF16}localizacao'), false, false, "", "", true, true);
$sideMenu->addMenuItem(9, "mi_status_documento", $Language->menuPhrase("9", "MenuText"), "StatusDocumentoList", 10, "", AllowListMenu('{E0FBA0D0-6EA0-4AAB-A8CC-5871C01EDF16}status_documento'), false, false, "", "", true, true);
$sideMenu->addMenuItem(41, "mci_Risco/Oportunidade", $Language->menuPhrase("41", "MenuText"), "", 10, "", true, false, true, "", "", true, true);
$sideMenu->addMenuItem(19, "mi_acao_risco_oportunidade", $Language->menuPhrase("19", "MenuText"), "AcaoRiscoOportunidadeList", 41, "", AllowListMenu('{E0FBA0D0-6EA0-4AAB-A8CC-5871C01EDF16}acao_risco_oportunidade'), false, false, "", "", true, true);
$sideMenu->addMenuItem(20, "mi_frequencia", $Language->menuPhrase("20", "MenuText"), "FrequenciaList", 41, "", AllowListMenu('{E0FBA0D0-6EA0-4AAB-A8CC-5871C01EDF16}frequencia'), false, false, "", "", true, true);
$sideMenu->addMenuItem(21, "mi_impacto", $Language->menuPhrase("21", "MenuText"), "ImpactoList", 41, "", AllowListMenu('{E0FBA0D0-6EA0-4AAB-A8CC-5871C01EDF16}impacto'), false, false, "", "", true, true);
$sideMenu->addMenuItem(22, "mi_origem_risco_oportunidade", $Language->menuPhrase("22", "MenuText"), "OrigemRiscoOportunidadeList", 41, "", AllowListMenu('{E0FBA0D0-6EA0-4AAB-A8CC-5871C01EDF16}origem_risco_oportunidade'), false, false, "", "", true, true);
$sideMenu->addMenuItem(42, "mi_periodicidade", $Language->menuPhrase("42", "MenuText"), "PeriodicidadeList", 41, "", AllowListMenu('{E0FBA0D0-6EA0-4AAB-A8CC-5871C01EDF16}periodicidade'), false, false, "", "", true, true);
$sideMenu->addMenuItem(24, "mi_status_acao", $Language->menuPhrase("24", "MenuText"), "StatusAcaoList", 41, "", AllowListMenu('{E0FBA0D0-6EA0-4AAB-A8CC-5871C01EDF16}status_acao'), false, false, "", "", true, true);
$sideMenu->addMenuItem(174, "mi_tipo", $Language->menuPhrase("174", "MenuText"), "TipoList", 10, "", AllowListMenu('{E0FBA0D0-6EA0-4AAB-A8CC-5871C01EDF16}tipo'), false, false, "", "", true, true);
$sideMenu->addMenuItem(64, "mi_unidade_medida", $Language->menuPhrase("64", "MenuText"), "UnidadeMedidaList", 10, "", AllowListMenu('{E0FBA0D0-6EA0-4AAB-A8CC-5871C01EDF16}unidade_medida'), false, false, "", "", true, true);
$sideMenu->addMenuItem(11, "mci_Segurança", $Language->menuPhrase("11", "MenuText"), "", 10, "", true, false, true, "", "", true, true);
$sideMenu->addMenuItem(1, "mi_usuario", $Language->menuPhrase("1", "MenuText"), "UsuarioList", 11, "", AllowListMenu('{E0FBA0D0-6EA0-4AAB-A8CC-5871C01EDF16}usuario'), false, false, "", "", true, true);
$sideMenu->addMenuItem(53, "mi_UserLevels", $Language->menuPhrase("53", "MenuText"), "UserLevelsList", 11, "", AllowListMenu('{E0FBA0D0-6EA0-4AAB-A8CC-5871C01EDF16}UserLevels'), false, false, "", "", true, true);
$sideMenu->addMenuItem(16, "mci_Relatórios", $Language->menuPhrase("16", "MenuText"), "", -1, "", true, false, true, "", "", true, true);
$sideMenu->addMenuItem(55, "mi_rel_analise_swot", $Language->menuPhrase("55", "MenuText"), "RelAnaliseSwot", 16, "", AllowListMenu('{E0FBA0D0-6EA0-4AAB-A8CC-5871C01EDF16}rel_analise_swot'), false, false, "", "", true, true);
$sideMenu->addMenuItem(59, "mi_rel_cross_grafico", $Language->menuPhrase("59", "MenuText"), "RelCrossGrafico", 16, "", AllowListMenu('{E0FBA0D0-6EA0-4AAB-A8CC-5871C01EDF16}rel_cross_grafico'), false, false, "", "", true, true);
$sideMenu->addMenuItem(172, "mi_rel_view_plano_auditoria", $Language->menuPhrase("172", "MenuText"), "RelViewPlanoAuditoria", 16, "", AllowListMenu('{E0FBA0D0-6EA0-4AAB-A8CC-5871C01EDF16}rel_view_plano_auditoria'), false, false, "", "", true, true);
$sideMenu->addMenuItem(63, "mi_rel_processos", $Language->menuPhrase("63", "MenuText"), "RelProcessos", 16, "", AllowListMenu('{E0FBA0D0-6EA0-4AAB-A8CC-5871C01EDF16}rel_processos'), false, false, "", "", true, true);
$sideMenu->addMenuItem(62, "mi_rel_processo_indicador", $Language->menuPhrase("62", "MenuText"), "RelProcessoIndicador", 16, "", AllowListMenu('{E0FBA0D0-6EA0-4AAB-A8CC-5871C01EDF16}rel_processo_indicador'), false, false, "", "", true, true);
$sideMenu->addMenuItem(170, "mi_rel_view_aud_interna", $Language->menuPhrase("170", "MenuText"), "RelViewAudInterna", 16, "", AllowListMenu('{E0FBA0D0-6EA0-4AAB-A8CC-5871C01EDF16}rel_view_aud_interna'), false, false, "", "", true, true);
echo $sideMenu->toScript();
